// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using ApngPlayerBinding;

namespace MonoTestApngPlayer
{
	[Register ("AVAnimatorView")] 
	public partial class AVAnimatorView : ApngPlayerBinding.AVAnimatorView
	{
		public AVAnimatorView (IntPtr handle) : base (handle)
		{
			Console.WriteLine ("Initializing AVAnimatorView 1");
			Initialize ();
		}

		[Export("initWithCoder:")]		
		public AVAnimatorView (NSCoder coder) : base(coder)			
		{
			Console.WriteLine ("Initializing AVAnimatorView 2");
			Initialize ();			
		}

		public AVAnimatorView()
		{
			Console.WriteLine ("Initializing AVAnimatorView 3");
			Initialize ();			
		}

		void Initialize ()			
		{
			Console.WriteLine ("Initializing AVAnimatorView");
		}

	}
}
